import {Customer} from "./customer"

export const MockCustomerList: Customer[] = [
    {
        id: 0,
        firstName: "Albert",
        lastName: "Peterson",
        phone: "0176480828",
        email: "albert@peterson.de",
        billingAddress: {
            countryCode: "DEU",
            zipCode: 80339,
            state: "Bayern",
            city: "München",
            street: "Sonnenstraße",
            houseNumber: 1,
            recipient: "Albert Peterson",
        },
        deliveryAddress: {
            countryCode: "DEU",
            zipCode: 80339,
            state: "Bayern",
            city: "München",
            street: "Sonnenstraße",
            houseNumber: 1,
            recipient: "Albert Peterson",
        },
        ordersIds: [0,1],
    },
    {
        id: 1,
        firstName: "Max",
        lastName: "Mustermann",
        phone: "0165000000",
        email: "max@mustermann.de",
        billingAddress: {
            countryCode: "DEU",
            zipCode: 80339,
            state: "Bayern",
            city: "München",
            street: "Sonnenstraße",
            houseNumber: 3,
            recipient: "Max Mustermann",
        },
        deliveryAddress: {
            countryCode: "DEU",
            zipCode: 80339,
            state: "Bayern",
            city: "München",
            street: "Sonnenstraße",
            houseNumber: 3,
            recipient: "Max Mustermann",
        },
        ordersIds: [2],
    },
]