import { Order, OrderType, OrderStatus} from './order'

export const MockOrderList: Order[] = [
    {
        id: 0,
        customerId: 0,
        orderType: OrderType.PURCHASE,
        date: "2008-03-19T08:25:43+02:00",
        items: [
            {
                id: 0,
                articleId: 0,
                price: { amount: 10, currency: "€"},
                quantity: 1,
            },
        ],
        orderStatus: OrderStatus.ORDERED,
        billingAddress: {
            countryCode: "DEU",
            zipCode: 80339,
            state: "Bayern",
            city: "München",
            street: "Sonnenstraße",
            houseNumber: "1",
            recipient: "Mama",
        },
        deliveryAddress: {
            countryCode: "DEU",
            zipCode: 80339,
            state: "Bayern",
            city: "München",
            street: "Sonnenstraße",
            houseNumber: "1",
            recipient: "Albert Peterson",
        },
        comments: "Please beware of the dog in front of the house",
    },
    {
        id: 1,
        customerId: 0,
        orderType: OrderType.RENT,
        date: "2019-03-19T08:25:43+02:00",
        items: [
            {
                id: 0,
                articleId: 1,
                price: { amount: 5, currency: "€"},
                quantity: 89,
            },
        ],
        orderStatus: OrderStatus.ORDERED,
        billingAddress: {
            countryCode: "DEU",
            zipCode: 80339,
            state: "Bayern",
            city: "München",
            street: "Sonnenstraße",
            houseNumber: "1",
            recipient: "Albert Peterson",
        },
        deliveryAddress: {
            countryCode: "DEU",
            zipCode: 80339,
            state: "Bayern",
            city: "München",
            street: "Sonnenstraße",
            houseNumber: "1",
            recipient: "Albert Peterson",
        },
        comments: "Watch out for the elder woman in the house",
    },
    {
        id: 2,
        customerId: 1,
        orderType: OrderType.PURCHASE,
        date: "2020-03-19T08:25:43+02:00",
        items: [
            {
                id: 0,
                articleId: 2,
                price: { amount: 10000, currency: "$"},
                quantity: 3,
            },
            {
                id: 1,
                articleId: 3,
                price: { amount: 1000, currency: "$"},
                quantity: 4,
            },
        ],
        orderStatus: OrderStatus.RECEIVED,
        billingAddress: {
            countryCode: "DEU",
            zipCode: 80339,
            state: "Bayern",
            city: "München",
            street: "Sonnenstraße",
            houseNumber: "3",
            recipient: "Max Mustermann",
        },
        deliveryAddress: {
            countryCode: "DEU",
            zipCode: 80339,
            state: "Bayern",
            city: "München",
            street: "Sonnenstraße",
            houseNumber: "3",
            recipient: "Max Mustermann",
        },
        comments: "Watch out for the elder woman in the house",
    },
]